version: "2.4"

services:
  api:
    build:
      context: ./api
      target: dev
    environment:
      CGO_ENABLED: 0
      API_DB_HOST: db
      API_DB_DISABLE_TLS: "true"
      API_WEB_PRODUCTION: "false"
      API_WEB_ADDRESS: :$API_PORT
      API_WEB_DEBUG: :$PPROF_PORT
      API_WEB_READ_TIMEOUT: 7s
      API_WEB_WRITE_TIMEOUT: 7s
      API_WEB_SHUTDOWN_TIMEOUT: 7s
      API_WEB_FRONTEND_ADDRESS: $API_WEB_FRONTEND_ADDRESS
      API_WEB_AUTH_DOMAIN: $API_WEB_AUTH_DOMAIN
      API_WEB_AUTH_AUDIENCE: $API_WEB_AUTH_AUDIENCE
      API_WEB_AUTH_M_2_M_CLIENT: $API_WEB_AUTH_M_2_M_CLIENT
      API_WEB_AUTH_M_2_M_SECRET: $API_WEB_AUTH_M_2_M_SECRET
    volumes:
      - ./api:/api
    networks:
      - postgres-net
    depends_on:
      db:
        condition: service_healthy
    ports:
      - $API_PORT:$API_PORT
      - $PPROF_PORT:$PPROF_PORT
    # swap commands to disable live reload
    # command: go run ./cmd/api
    command: CompileDaemon --build="go build -o main ./cmd/api" -log-prefix=false --command=./main